site_name: EasySSD1306
site_description: Uma biblioteca para criar interfaces gráficas em displays OLED SSD1306
site_url: https://digitalfen.github.io/EasySSD1306
repo_url: https://github.com/digitalfen/EasySSD1306
repo_name: digitalfen/EasySSD1306
edit_uri: edit/main/docs/

theme:
  name: material
  language: pt-BR
  palette:
    primary: blue
  features:
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.integrate

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Início: index.md
  - Componentes:
    - TextView: components/text-view.md
    - ImageView: components/image-view.md
    - Navigation: components/navigation.md
    - LoadAnimation: components/load-animation.md
    - Alert: components/alert.md
    - TextAnimation: components/text-animation.md
    - ImageAnimation: components/image-animation.md
    - Prompt: components/prompt.md
  - Exemplos:
    - Básico: examples/basic.md
    - Avançado: examples/advanced.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/digitalfen
    - icon: fontawesome/brands/discord
plugins:
  - search
