site_name: EasySSD1306
site_description: A library for creating graphical interfaces on SSD1306 OLED displays
site_url: https://digitalfen.github.io/EasySSD1306/
repo_url: https://github.com/digitalfen/EasySSD1306
repo_name: digitalfen/EasySSD1306

theme:
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search

nav:
  - Home: index.md
  - Components:
    - TextView: components/text-view.md
    - ImageView: components/image-view.md
    - Navigation: components/navigation.md
    - LoadAnimation: components/load-animation.md
    - Alert: components/alert.md
    - TextAnimation: components/text-animation.md
    - ImageAnimation: components/image-animation.md
    - Prompt: components/prompt.md
  - Examples:
    - Basic: examples/basic.md
    - Advanced: examples/advanced.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/digitalfen/EasySSD1306
  generator: false
