site_name: EasySSD1306
site_description: SSD1306 OLED Display Library
site_url: https://digitalfen.github.io/EasySSD1306/

theme:
  name: material
  language: en
  palette:
    primary: blue

markdown_extensions:
  - tables
  - attr_list
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - pymdownx.details

plugins:
  - search

nav:
  - Overview: index.md
  - Getting Started: getting_started.md
  - Display Manager:
    - Overview: display_manager/overview.md
    - Utilization: display_manager/utilization.md
    - Configurations:
      - Resolution: display_manager/resolution.md
      - Orientation: display_manager/orientation.md
      - Color: display_manager/color.md
      - Font: display_manager/font.md
      - Contrast: display_manager/contrast.md
      - Animation: display_manager/animation.md
      - Screen Saver: display_manager/screensaver.md
  - Components:
    - Overview: components/overview.md
    - Component Base: components/component.md
    - Display Manager: components/display-manager.md
    - Pre-built:
      - TextView: components/text-view.md
      - ImageView: components/image-view.md
      - LoadAnimation: components/load-animation.md
      - TextAnimation: components/text-animation.md
      - ImageAnimation: components/image-animation.md
      - Alert: components/alert.md
      - Prompt: components/prompt.md
      - Navigation: components/navigation.md
  - API Reference: api-reference.md
  - Examples: 
    - Basic: examples/basic.md
    - Advanced: examples/advanced.md
    - Resolution: examples/resolution.md
    - Orientation: examples/orientation.md
    - Navigation: examples/navigation.md
    - Load Animation: examples/load_animation.md
    - Alert: examples/alert.md
  - Contributing: contributing.md
  - License: license.md
