site_name: EasySSD1306
site_description: A library for creating graphical interfaces on SSD1306 OLED displays
site_url: https://digitalfen.github.io/EasySSD1306
repo_url: https://github.com/digitalfen/EasySSD1306
repo_name: digitalfen/EasySSD1306
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy

markdown_extensions:
  - codehilite
  - fenced_code
  - tables
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Home: index.md
  - Quick Start: quickstart.md
  - Components:
    - Overview: components/overview.md
    - TextView: components/text-view.md
    - TextAnimation: components/text-animation.md
    - Navigation: components/navigation.md
    - ImageView: components/image-view.md
    - ImageAnimation: components/image-animation.md
    - LoadAnimation: components/load-animation.md
    - Alert: components/alert.md
    - Prompt: components/prompt.md
  - Examples: examples.md
  - API Reference: api-reference.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/digitalfen
    - icon: fontawesome/brands/discord
      link: https://discord.gg/your-server

plugins:
  - search
