site_name: EasySSD1306
site_description: A library for creating graphical interfaces on SSD1306 OLED displays
site_url: https://digitalfen.github.io/EasySSD1306
repo_url: https://github.com/digitalfen/EasySSD1306
repo_name: digitalfen/EasySSD1306
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

markdown_extensions:
  - codehilite:
      guess_lang: false
  - fenced_code
  - tables
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - Quick Start: quickstart.md
  - Components:
    - Overview: components/overview.md
    - TextView: components/text-view.md
    - TextAnimation: components/text-animation.md
    - Navigation: components/navigation.md
    - ImageView: components/image-view.md
    - ImageAnimation: components/image-animation.md
    - LoadAnimation: components/load-animation.md
    - Alert: components/alert.md
    - Prompt: components/prompt.md
  - Examples: examples.md
  - API Reference: api-reference.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/digitalfen
    - icon: fontawesome/brands/discord
      link: https://discord.gg/your-server
  version:
    provider: mike

plugins:
  - search
  - minify:
      minify_html: true
